# Generated by Django 4.2.5 on 2023-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('fak_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('ims', models.CharField(db_column='IMS', max_length=255)),
            ],
            options={
                'db_table': 'faculties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stud_id', models.IntegerField()),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fak_id', models.IntegerField()),
                ('gruppa', models.CharField(max_length=255)),
                ('course', models.IntegerField()),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, db_column='STUDENT_ID', null=True)),
                ('student_fio', models.CharField(blank=True, db_column='STUDENT_FIO', max_length=100, null=True)),
                ('gruppa', models.IntegerField(blank=True, db_column='GRUPPA', null=True)),
                ('discipline_name', models.TextField(blank=True, db_column='DISCIPLINE_NAME', null=True)),
                ('mark_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_examen', models.IntegerField(blank=True, db_column='IS_EXAMEN', null=True)),
                ('number_of_semester', models.IntegerField(blank=True, db_column='NUMBER_OF_SEMESTER', null=True)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('coddis', models.CharField(blank=True, db_column='CODDIS', max_length=50, null=True)),
                ('stud_id', models.IntegerField()),
            ],
            options={
                'db_table': 'marks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('fio', models.TextField()),
                ('spec', models.TextField(blank=True, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('tel', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('spec_napravl', models.TextField(blank=True, null=True)),
                ('forma', models.CharField(blank=True, max_length=20, null=True)),
                ('sroki', models.TextField(blank=True, null=True)),
                ('facultet', models.TextField(blank=True, null=True)),
                ('kafedra', models.CharField(blank=True, max_length=50, null=True)),
                ('rukov', models.CharField(blank=True, max_length=50, null=True)),
                ('tema', models.CharField(blank=True, max_length=100, null=True)),
                ('gruppa', models.IntegerField(blank=True, null=True)),
                ('edecanat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('fac_id', models.IntegerField(blank=True, null=True)),
                ('course', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metric1', models.PositiveIntegerField()),
                ('metric2', models.PositiveIntegerField()),
                ('metric3', models.PositiveIntegerField()),
                ('metric4', models.PositiveIntegerField()),
                ('metric5', models.PositiveIntegerField()),
            ],
        ),
    ]
