# Generated by Django 4.2.5 on 2023-09-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cogn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
