# Generated by Django 4.2.5 on 2023-10-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogn', '0002_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kod_plana', models.PositiveIntegerField()),
                ('stud_plan', models.PositiveIntegerField()),
                ('comp_name', models.CharField(max_length=255)),
                ('shifr_name', models.CharField(max_length=255)),
                ('order', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelTable(
            name='student',
            table='cogn_student',
        ),
    ]
